package com.dasha.parser.entity.element;

/**
 * Created by Даша on 23.01.2017.
 */
public enum WebTagName {
    WEB_APP, DISPLAY_NAME, WELCOME_FILE_LIST, WELCOME_FILE, FILTER,
    FILTER_NAME, FILTER_CLASS, INIT_PARAM,PARAM_NAME, PARAM_VALUE,
    FILTER_MAPPING, URL_PATTERN, DISPATCHER, LISTENER, LISTENER_CLASS,
    SERVLET, SERVLET_NAME, SERVLET_CLASS, SERVLET_MAPPING, ERROR_PAGE,
    EXCEPTION_TYPE, LOCATION, ERROR_CODE
}
